import type { QueryType } from "./classify.ts";

export type ToolGroupId =
  | "best"
  | "us-records"
  | "accounts"
  | "web"
  | "infra"
  | "advanced";

export type ToolRegion = "us" | "global";

export type Tool = {
  id: string;
  name: string;
  homepage: string;
  urlTemplate: string;
  types: QueryType[];
  region: ToolRegion;
  blurb: string;
  weight: number;
  group: Exclude<ToolGroupId, "best">;
  paid?: boolean;
};

/**
 * Placeholders in urlTemplate:
 * Identity fields are required for a prefilled URL; location fields are optional.
 * {name} {first} {last} {email} {phone} {phoneDigits} {phoneDashed} {phoneNational}
 * {username} {domain} {ip} {url} {query} {address} {addressSlug} {nameSlug} {nameHyphen}
 * {city} {state} {zip} {citystatezip} {quotedName} {quotedEmail} {quotedQuery}
 */
export const TOOLS: Tool[] = [
  {
    id: "google",
    name: "Google",
    homepage: "https://www.google.com/",
    urlTemplate: "https://www.google.com/search?q={query}",
    types: ["person_name", "email", "phone", "username", "us_address", "domain", "url", "unknown"],
    region: "global",
    blurb: "Broad web search. Start here, then narrow.",
    weight: 100,
    group: "web",
  },
  {
    id: "duckduckgo",
    name: "DuckDuckGo",
    homepage: "https://duckduckgo.com/",
    urlTemplate: "https://duckduckgo.com/?q={query}",
    types: ["person_name", "email", "phone", "username", "us_address", "domain", "url", "unknown"],
    region: "global",
    blurb: "Independent web search with fewer tracking parameters.",
    weight: 80,
    group: "web",
  },
  {
    id: "bing",
    name: "Bing",
    homepage: "https://www.bing.com/",
    urlTemplate: "https://www.bing.com/search?q={query}",
    types: ["person_name", "email", "phone", "username", "us_address", "domain", "unknown"],
    region: "global",
    blurb: "Second index. Sometimes surfaces different people-search snippets.",
    weight: 70,
    group: "web",
  },
  {
    id: "truepeoplesearch",
    name: "TruePeopleSearch",
    homepage: "https://www.truepeoplesearch.com/",
    urlTemplate: "https://www.truepeoplesearch.com/results?name={name}&citystatezip={citystatezip}",
    types: ["person_name"],
    region: "us",
    blurb: "US people-search index. Public listings, not a background check.",
    weight: 95,
    group: "us-records",
  },
  {
    id: "truepeoplesearch-phone",
    name: "TruePeopleSearch (phone)",
    homepage: "https://www.truepeoplesearch.com/",
    urlTemplate: "https://www.truepeoplesearch.com/results?phoneno={phoneNational}",
    types: ["phone"],
    region: "us",
    blurb: "Reverse-phone lookup on a public US people-search site.",
    weight: 94,
    group: "us-records",
  },
  {
    id: "truepeoplesearch-address",
    name: "TruePeopleSearch (address)",
    homepage: "https://www.truepeoplesearch.com/",
    urlTemplate: "https://www.truepeoplesearch.com/results?streetaddress={address}&citystatezip={citystatezip}",
    types: ["us_address"],
    region: "us",
    blurb: "Address lookup against public US listings.",
    weight: 93,
    group: "us-records",
  },
  {
    id: "fastpeoplesearch",
    name: "FastPeopleSearch",
    homepage: "https://www.fastpeoplesearch.com/",
    urlTemplate: "https://www.fastpeoplesearch.com/name/{nameSlug}",
    types: ["person_name"],
    region: "us",
    blurb: "US name search. Data is unverified and often stale.",
    weight: 90,
    group: "us-records",
  },
  {
    id: "fastpeoplesearch-phone",
    name: "FastPeopleSearch (phone)",
    homepage: "https://www.fastpeoplesearch.com/",
    urlTemplate: "https://www.fastpeoplesearch.com/{phoneDashed}",
    types: ["phone"],
    region: "us",
    blurb: "Reverse phone pages on FastPeopleSearch.",
    weight: 88,
    group: "us-records",
  },
  {
    id: "thatsthem",
    name: "That'sThem",
    homepage: "https://thatsthem.com/",
    urlTemplate: "https://thatsthem.com/name/{nameHyphen}",
    types: ["person_name"],
    region: "us",
    blurb: "Public people, email, and phone index.",
    weight: 86,
    group: "us-records",
  },
  {
    id: "thatsthem-email",
    name: "That'sThem (email)",
    homepage: "https://thatsthem.com/",
    urlTemplate: "https://thatsthem.com/email/{email}",
    types: ["email"],
    region: "us",
    blurb: "Email-to-public-record lookup. Treat hits as leads, not proof.",
    weight: 84,
    group: "accounts",
  },
  {
    id: "thatsthem-phone",
    name: "That'sThem (phone)",
    homepage: "https://thatsthem.com/",
    urlTemplate: "https://thatsthem.com/phone/{phoneDashed}",
    types: ["phone"],
    region: "us",
    blurb: "Reverse phone on That'sThem.",
    weight: 82,
    group: "us-records",
  },
  {
    id: "searchpeoplefree",
    name: "SearchPeopleFree",
    homepage: "https://www.searchpeoplefree.com/",
    urlTemplate: "https://www.searchpeoplefree.com/find/{nameSlug}",
    types: ["person_name"],
    region: "us",
    blurb: "Free US people-search pages assembled from public sources.",
    weight: 78,
    group: "us-records",
  },
  {
    id: "whitepages",
    name: "Whitepages",
    homepage: "https://www.whitepages.com/",
    urlTemplate: "https://www.whitepages.com/name/{nameHyphen}",
    types: ["person_name"],
    region: "us",
    blurb: "Directory-style name search. Paid upsells are optional.",
    weight: 76,
    group: "us-records",
  },
  {
    id: "whitepages-phone",
    name: "Whitepages (phone)",
    homepage: "https://www.whitepages.com/",
    urlTemplate: "https://www.whitepages.com/phone/{phoneDashed}",
    types: ["phone"],
    region: "us",
    blurb: "Reverse phone directory.",
    weight: 75,
    group: "us-records",
  },
  {
    id: "usphonebook",
    name: "USPhoneBook",
    homepage: "https://www.usphonebook.com/",
    urlTemplate: "https://www.usphonebook.com/{nameHyphen}",
    types: ["person_name"],
    region: "us",
    blurb: "US phone-book style listings by name.",
    weight: 72,
    group: "us-records",
  },
  {
    id: "usphonebook-phone",
    name: "USPhoneBook (phone)",
    homepage: "https://www.usphonebook.com/",
    urlTemplate: "https://www.usphonebook.com/{phoneDashed}",
    types: ["phone"],
    region: "us",
    blurb: "Reverse phone book.",
    weight: 71,
    group: "us-records",
  },
  {
    id: "familytreenow",
    name: "FamilyTreeNow",
    homepage: "https://www.familytreenow.com/",
    urlTemplate: "https://www.familytreenow.com/search/genealogy/results?first={first}&last={last}&city={city}&state={state}",
    types: ["person_name"],
    region: "us",
    blurb: "Genealogy-oriented public records. Not an identity proof.",
    weight: 74,
    group: "us-records",
  },
  {
    id: "nuwber",
    name: "Nuwber",
    homepage: "https://nuwber.com/",
    urlTemplate: "https://nuwber.com/search?name={name}&city={city}&state={state}",
    types: ["person_name"],
    region: "us",
    blurb: "People-search aggregator. Listings are unverified.",
    weight: 68,
    group: "us-records",
  },
  {
    id: "idcrawl",
    name: "IDCrawl",
    homepage: "https://www.idcrawl.com/",
    urlTemplate: "https://www.idcrawl.com/{nameSlug}",
    types: ["person_name"],
    region: "us",
    blurb: "Name search plus social-profile clustering.",
    weight: 69,
    group: "us-records",
  },
  {
    id: "idcrawl-username",
    name: "IDCrawl (username)",
    homepage: "https://www.idcrawl.com/",
    urlTemplate: "https://www.idcrawl.com/u/{username}",
    types: ["username"],
    region: "us",
    blurb: "Username crawl across public sites.",
    weight: 73,
    group: "accounts",
  },
  {
    id: "property-assessor",
    name: "County property assessor",
    homepage: "https://www.google.com/",
    urlTemplate: "https://www.google.com/search?q={quotedName}+{quotedCity}+{state}+property+assessor",
    types: ["person_name", "us_address"],
    region: "us",
    blurb: "Google template for the local county assessor. Ownership records, not identity.",
    weight: 66,
    group: "us-records",
  },
  {
    id: "zillow",
    name: "Zillow",
    homepage: "https://www.zillow.com/",
    urlTemplate: "https://www.zillow.com/homes/{addressSlug}_rb/",
    types: ["us_address"],
    region: "us",
    blurb: "Property listing page for an address. Not a people search.",
    weight: 64,
    group: "us-records",
  },
  {
    id: "redfin",
    name: "Redfin",
    homepage: "https://www.redfin.com/",
    urlTemplate: "https://www.redfin.com/q/{address}",
    types: ["us_address"],
    region: "us",
    blurb: "Listing search for an address. Housing data, not identity.",
    weight: 63,
    group: "us-records",
  },
  {
    id: "hibp",
    name: "Have I Been Pwned",
    homepage: "https://haveibeenpwned.com/",
    urlTemplate: "https://haveibeenpwned.com/account/{email}",
    types: ["email"],
    region: "global",
    blurb: "Check whether an email appears in known breaches. We do not call the API or show dump contents.",
    weight: 92,
    group: "accounts",
  },
  {
    id: "epieos",
    name: "Epieos",
    homepage: "https://epieos.com/",
    urlTemplate: "https://epieos.com/?q={email}",
    types: ["email"],
    region: "global",
    blurb: "Email and phone OSINT helper. Review their terms before searching.",
    weight: 77,
    group: "accounts",
  },
  {
    id: "intelx",
    name: "Intelligence X",
    homepage: "https://intelx.io/",
    urlTemplate: "https://intelx.io/?s={query}",
    types: ["email", "domain", "username", "phone", "ipv4", "ipv6"],
    region: "global",
    blurb: "Selectors search across public and leaked sources. We do not display dumps.",
    weight: 65,
    group: "accounts",
  },
  {
    id: "dehashed",
    name: "Dehashed",
    homepage: "https://dehashed.com/",
    urlTemplate: "https://dehashed.com/search?query={query}",
    types: ["email", "username", "phone", "domain"],
    region: "global",
    blurb: "Paid breach-index search. Outbound only; Plainview never shows dump contents.",
    weight: 40,
    group: "advanced",
    paid: true,
  },
  {
    id: "hunter",
    name: "Hunter.io",
    homepage: "https://hunter.io/",
    urlTemplate: "https://hunter.io/search/{domain}",
    types: ["domain", "email"],
    region: "global",
    blurb: "Domain email-pattern search used for professional outreach research.",
    weight: 62,
    group: "accounts",
  },
  {
    id: "gravatar",
    name: "Gravatar",
    homepage: "https://gravatar.com/",
    urlTemplate: "https://gravatar.com/{email}",
    types: ["email"],
    region: "global",
    blurb: "Public profile attached to an email hash. Presence is not a confirmed identity.",
    weight: 60,
    group: "accounts",
  },
  {
    id: "google-email",
    name: "Google (quoted email)",
    homepage: "https://www.google.com/",
    urlTemplate: "https://www.google.com/search?q={quotedEmail}",
    types: ["email"],
    region: "global",
    blurb: "Exact-match web search for the email address.",
    weight: 91,
    group: "web",
  },
  {
    id: "whatsmyname",
    name: "WhatsMyName",
    homepage: "https://whatsmyname.app/",
    urlTemplate: "https://whatsmyname.app/?q={username}",
    types: ["username"],
    region: "global",
    blurb: "Username reuse across hundreds of sites.",
    weight: 89,
    group: "accounts",
  },
  {
    id: "instantusername",
    name: "Instant Username Search",
    homepage: "https://instantusername.com/",
    urlTemplate: "https://instantusername.com/#/{username}",
    types: ["username"],
    region: "global",
    blurb: "Availability and presence of a handle on popular networks.",
    weight: 70,
    group: "accounts",
  },
  {
    id: "namechk",
    name: "Namechk",
    homepage: "https://namechk.com/",
    urlTemplate: "https://namechk.com/namechk-search/?n={username}&as=standard",
    types: ["username"],
    region: "global",
    blurb: "Handle check across domains and social networks.",
    weight: 67,
    group: "accounts",
  },
  {
    id: "github-user",
    name: "GitHub",
    homepage: "https://github.com/",
    urlTemplate: "https://github.com/{username}",
    types: ["username"],
    region: "global",
    blurb: "Public GitHub profile if the handle exists.",
    weight: 85,
    group: "accounts",
  },
  {
    id: "reddit-user",
    name: "Reddit",
    homepage: "https://www.reddit.com/",
    urlTemplate: "https://www.reddit.com/user/{username}",
    types: ["username"],
    region: "global",
    blurb: "Public Reddit profile URL for the handle.",
    weight: 64,
    group: "accounts",
  },
  {
    id: "x-user",
    name: "X / Twitter",
    homepage: "https://x.com/",
    urlTemplate: "https://x.com/{username}",
    types: ["username"],
    region: "global",
    blurb: "Public X profile URL. Does not confirm the person behind the handle.",
    weight: 83,
    group: "accounts",
  },
  {
    id: "linkedin-user",
    name: "LinkedIn (in/)",
    homepage: "https://www.linkedin.com/",
    urlTemplate: "https://www.linkedin.com/in/{username}",
    types: ["username"],
    region: "global",
    blurb: "Guesses a LinkedIn vanity URL from the handle.",
    weight: 61,
    group: "accounts",
  },
  {
    id: "instagram-user",
    name: "Instagram",
    homepage: "https://www.instagram.com/",
    urlTemplate: "https://www.instagram.com/{username}/",
    types: ["username"],
    region: "global",
    blurb: "Public Instagram profile URL.",
    weight: 72,
    group: "accounts",
  },
  {
    id: "tiktok-user",
    name: "TikTok",
    homepage: "https://www.tiktok.com/",
    urlTemplate: "https://www.tiktok.com/@{username}",
    types: ["username"],
    region: "global",
    blurb: "Public TikTok profile URL.",
    weight: 58,
    group: "accounts",
  },
  {
    id: "youtube-user",
    name: "YouTube",
    homepage: "https://www.youtube.com/",
    urlTemplate: "https://www.youtube.com/@{username}",
    types: ["username"],
    region: "global",
    blurb: "YouTube handle URL.",
    weight: 57,
    group: "accounts",
  },
  {
    id: "inteltechniques-username",
    name: "IntelTechniques (username)",
    homepage: "https://inteltechniques.com/tools/Username.html",
    urlTemplate: "https://inteltechniques.com/tools/Username.html",
    types: ["username"],
    region: "global",
    blurb: "Michael Bazzell’s username tools. Copy the handle, then search on-site.",
    weight: 55,
    group: "accounts",
  },
  {
    id: "google-news",
    name: "Google News",
    homepage: "https://news.google.com/",
    urlTemplate: "https://news.google.com/search?q={query}",
    types: ["person_name", "domain"],
    region: "global",
    blurb: "News mentions. Common names will collide.",
    weight: 71,
    group: "web",
  },
  {
    id: "linkedin-people",
    name: "LinkedIn people search",
    homepage: "https://www.linkedin.com/",
    urlTemplate: "https://www.linkedin.com/search/results/people/?keywords={name}",
    types: ["person_name"],
    region: "global",
    blurb: "Professional directory search. Requires a LinkedIn session for full results.",
    weight: 87,
    group: "web",
  },
  {
    id: "facebook-people",
    name: "Facebook people search",
    homepage: "https://www.facebook.com/",
    urlTemplate: "https://www.facebook.com/search/people/?q={name}",
    types: ["person_name"],
    region: "global",
    blurb: "People search on Facebook. Results depend on your session and their privacy settings.",
    weight: 79,
    group: "web",
  },
  {
    id: "courtlistener",
    name: "CourtListener",
    homepage: "https://www.courtlistener.com/",
    urlTemplate: "https://www.courtlistener.com/?q={name}&type=r&order_by=score+desc",
    types: ["person_name"],
    region: "us",
    blurb: "Free law project search of public US court documents. Many names will miss.",
    weight: 73,
    group: "web",
  },
  {
    id: "opencorporates",
    name: "OpenCorporates",
    homepage: "https://opencorporates.com/",
    urlTemplate: "https://opencorporates.com/officers?q={name}",
    types: ["person_name", "domain"],
    region: "global",
    blurb: "Company officer search in public company registers.",
    weight: 72,
    group: "web",
  },
  {
    id: "fec",
    name: "FEC individual contributions",
    homepage: "https://www.fec.gov/data/receipts/individual-contributions/",
    urlTemplate: "https://www.fec.gov/data/receipts/individual-contributions/?contributor_name={name}&min_date=01%2F01%2F2000",
    types: ["person_name"],
    region: "us",
    blurb: "US federal campaign-finance receipts. Public, federal only.",
    weight: 68,
    group: "web",
  },
  {
    id: "webmii",
    name: "WebMii",
    homepage: "https://webmii.com/",
    urlTemplate: "https://webmii.com/people?n={name}",
    types: ["person_name"],
    region: "global",
    blurb: "Weak extra people-web index. Useful as a second pass, not a source of truth.",
    weight: 42,
    group: "web",
  },
  {
    id: "inteltechniques-name",
    name: "IntelTechniques (name)",
    homepage: "https://inteltechniques.com/tools/Search.html",
    urlTemplate: "https://inteltechniques.com/tools/Search.html",
    types: ["person_name"],
    region: "global",
    blurb: "Name-search workbook. Copy the name; the page does not take a query string.",
    weight: 54,
    group: "web",
  },
  {
    id: "spydialer",
    name: "SpyDialer",
    homepage: "https://www.spydialer.com/",
    urlTemplate: "https://www.spydialer.com/",
    types: ["phone"],
    region: "us",
    blurb: "Reverse-phone and owner-name clues. Copy the number; on-site search required.",
    weight: 70,
    group: "accounts",
  },
  {
    id: "inteltechniques-phone",
    name: "IntelTechniques (phone)",
    homepage: "https://inteltechniques.com/tools/Telephone.html",
    urlTemplate: "https://inteltechniques.com/tools/Telephone.html",
    types: ["phone"],
    region: "global",
    blurb: "Phone OSINT workbook. Copy the number into the page.",
    weight: 52,
    group: "accounts",
  },
  {
    id: "google-ip",
    name: "Google (host/IP)",
    homepage: "https://www.google.com/",
    urlTemplate: "https://www.google.com/search?q={ip}",
    types: ["ipv4", "ipv6"],
    region: "global",
    blurb: "Web mentions of the address.",
    weight: 50,
    group: "infra",
  },
  {
    id: "crtsh",
    name: "crt.sh",
    homepage: "https://crt.sh/",
    urlTemplate: "https://crt.sh/?q={domain}",
    types: ["domain"],
    region: "global",
    blurb: "Certificate transparency names for a domain.",
    weight: 88,
    group: "infra",
  },
  {
    id: "rdap-lookup",
    name: "RDAP",
    homepage: "https://lookup.icann.org/",
    urlTemplate: "https://lookup.icann.org/en/lookup?q={domain}",
    types: ["domain"],
    region: "global",
    blurb: "ICANN registration lookup (registrar and dates).",
    weight: 86,
    group: "infra",
  },
  {
    id: "securitytrails-dns",
    name: "ViewDNS",
    homepage: "https://viewdns.info/",
    urlTemplate: "https://viewdns.info/whois/?domain={domain}",
    types: ["domain"],
    region: "global",
    blurb: "Public WHOIS/view of a domain.",
    weight: 60,
    group: "infra",
  },
  {
    id: "urlscan",
    name: "urlscan.io",
    homepage: "https://urlscan.io/",
    urlTemplate: "https://urlscan.io/domain/{domain}",
    types: ["domain", "url"],
    region: "global",
    blurb: "Public scans and related infrastructure for a host.",
    weight: 58,
    group: "infra",
  },
  {
    id: "osint-industries",
    name: "OSINT Industries",
    homepage: "https://app.osint.industries/",
    urlTemplate: "https://app.osint.industries/",
    types: ["email", "phone", "username", "person_name"],
    region: "global",
    blurb: "Paid OSINT platform. Outbound only; we do not query it.",
    weight: 30,
    group: "advanced",
    paid: true,
  },
  {
    id: "pimeyes",
    name: "PimEyes",
    homepage: "https://pimeyes.com/en",
    urlTemplate: "https://pimeyes.com/en",
    types: ["person_name"],
    region: "global",
    blurb: "Face-search site. Plainview does not upload photos or run biometric search.",
    weight: 20,
    group: "advanced",
    paid: true,
  },
  {
    id: "maltego",
    name: "Maltego",
    homepage: "https://www.maltego.com/",
    urlTemplate: "https://www.maltego.com/",
    types: ["person_name", "email", "domain", "phone", "username"],
    region: "global",
    blurb: "Desktop link-analysis tool. Not a search box.",
    weight: 18,
    group: "advanced",
    paid: true,
  },
  {
    id: "shodan",
    name: "Shodan",
    homepage: "https://www.shodan.io/",
    urlTemplate: "https://www.shodan.io/host/{ip}",
    types: ["ipv4", "ipv6"],
    region: "global",
    blurb: "Internet-exposed services for an IP. Infrastructure, not a person.",
    weight: 84,
    group: "advanced",
    paid: true,
  },
  {
    id: "shodan-domain",
    name: "Shodan (hostname)",
    homepage: "https://www.shodan.io/",
    urlTemplate: "https://www.shodan.io/search?query=hostname%3A{domain}",
    types: ["domain"],
    region: "global",
    blurb: "Host search on Shodan.",
    weight: 50,
    group: "advanced",
    paid: true,
  },
  {
    id: "inteltechniques-index",
    name: "IntelTechniques toolkit",
    homepage: "https://inteltechniques.com/tools/",
    urlTemplate: "https://inteltechniques.com/tools/",
    types: ["person_name", "email", "phone", "username", "domain", "us_address"],
    region: "global",
    blurb: "Index of specialized OSINT search tools.",
    weight: 48,
    group: "advanced",
  },
  {
    id: "spokeo",
    name: "Spokeo",
    homepage: "https://www.spokeo.com/",
    urlTemplate: "https://www.spokeo.com/{nameHyphen}",
    types: ["person_name"],
    region: "us",
    blurb: "People-search aggregator. Not a screening product.",
    weight: 25,
    group: "advanced",
    paid: true,
  },
];

export const GROUP_META: { id: ToolGroupId; title: string; hint?: string }[] = [
  { id: "best", title: "Best first moves" },
  { id: "us-records", title: "US records" },
  { id: "accounts", title: "Email / phone / username" },
  { id: "web", title: "Web and news" },
  { id: "infra", title: "Infrastructure", hint: "Host and network sources — not a person." },
  { id: "advanced", title: "Advanced / paid", hint: "Outbound platforms. We do not run these searches for you." },
];
