/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ApiLookupRouteImport } from './routes/api/lookup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupRoute = ApiLookupRouteImport.update({
  id: '/api/lookup',
  path: '/api/lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/search': typeof SearchRoute
  '/tools': typeof ToolsRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/legal' | '/search' | '/tools' | '/api/lookup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/legal' | '/search' | '/tools' | '/api/lookup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/legal'
    | '/search'
    | '/tools'
    | '/api/lookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LegalRoute: typeof LegalRoute
  SearchRoute: typeof SearchRoute
  ToolsRoute: typeof ToolsRoute
  ApiLookupRoute: typeof ApiLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup': {
      id: '/api/lookup'
      path: '/api/lookup'
      fullPath: '/api/lookup'
      preLoaderRoute: typeof ApiLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LegalRoute: LegalRoute,
  SearchRoute: SearchRoute,
  ToolsRoute: ToolsRoute,
  ApiLookupRoute: ApiLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
